### PR TITLE
[include] More Subjects 

### PR DESCRIPTION
**Pull request by amanchandra333**
There are multiple commits because I'm a beginner and I messed up a bit in the beginning, and wasn't able to squash them all in one.

### CODE REVIEW

**Comment by icyflame** [comment]
@amanchandra333 Squash all your commits into one. Use `git rebase -i`. Diff LGTM.

**Comment by icyflame** [comment]
Diff LGTM. @amanchandra333 Squash your commits into one single commit with a message that says `Added subject code AB12345`.

**Comment by raivivek** [comment]
@icyflame I think you can just squash-merge from GitHub itself. Should be fine.

**Comment by icyflame** [comment]
@vivekiitkgp Yeah, this feature is handy. 

@amanchandra333 Thanks for the PR. :+1:

**Pull request merged**
