### PR TITLE
[include] More subjects

### PR DESCRIPTION
**Pull request by pranitbauva1997**
Second and third year mining courses have been included.

### CODE REVIEW

**Comment by athityakumar** [comment]
@pranitbauva1997 : LGTM.
@icyflame : Any comments?

**Comment by icyflame** [comment]
@athityakumar Can you put in a script to test if there are any duplicates being added?

**Comment by pranitbauva1997** [comment]
@icyflame I could try it after mid sems in a separate PR.

**Comment by athityakumar** [comment]
@icyflame : Moved it to issue #14. Merging this now & will write the script by today.

**Comment by athityakumar** [comment]
@icyflame : Anyway, as it's all stored as a hash, detecting copies would be difficult - but rather we can write a script to overwrite on the subjects.json file by looking at the change-log provided by `test_subjects.rb`.

**Pull request merged**
