### PR TITLE
[include] More Subjects

### PR DESCRIPTION
**Pull request by amanchandra333**

### CODE REVIEW

**Comment by pranitbauva1997** [comment]
@amanchandra333 Looks good, +1! Thanks for agreeing to help by including more subjects!

**Comment by icyflame** [comment]
@amanchandra333 Fix formatting of the JSON file (use the pretty print Ruby script if you need to)

**Comment by hargup** [comment]
@icyflame Github now allows you to directly make changes in the contributor's branch (see the pencil button on the top right corner of the diff), in cases these where it is trivial for you to make the change and pretty difficult for the contributor you should directly make the change to the PR. Anyway formatting issues should be non blocking.

**Comment by hargup** [comment]
@amanchandra333 Thanks for the pull request, @icyflame @pranitbauva1997 thanks for the review.

**Pull request merged**
